<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="pos-f-t">
    <div class="collapse" id="navbarToggleExternalContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="index.php">Inicio <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Lenguajes
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="index.php?ctl=squirrel">Squirrel</a>
            <a class="dropdown-item" href="index.php?ctl=cpp">C++</a>
            <a class="dropdown-item" href="index.php?ctl=csharp">C#</a>
            <a class="dropdown-item" href="index.php?ctl=java">Java</a>
          </div>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="index.php?ctl=about">Sobre este sitio</a>
        </li>
      </ul>
    </div>
    <nav class="navbar">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
        aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="index.php">Inicio <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Lenguajes
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="index.php?ctl=squirrel">Squirrel</a>
          <a class="dropdown-item" href="index.php?ctl=cpp">C++</a>
          <a class="dropdown-item" href="index.php?ctl=csharp">C#</a>
          <a class="dropdown-item" href="index.php?ctl=java">Java</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="index.php?ctl=about">Sobre este sitio</a>
      </li>
    </ul>
  </div>
</nav>