<div class="contenido">

        <div class="card" style="width: 18rem;">
                <img src="includes/content/resources/img/squirrel.png" class="card-img-top" alt="squirrel">
                <div class="card-body">
                        <h5 class="card-title">Squirrel</h5>
                        <p class="card-text">Squirrel (ardilla en inglés) es un lenguaje de programación de alto nivel
                                imperativo y diseñado para que sea ligero. Es fácilmente integrable en aplicaciones, lo
                                que lo
                                convierte en un sustituto apropiado de Lua o JavaScript. </p>
                        <a href="index.php?ctl=squirrel" class="btn btn-primary">Leer más</a>
                </div>
        </div>

        <div class="card" style="width: 18rem;">
                <img src="includes/content/resources/img/cpp.jpg" class="card-img-top" alt="cpp">
                <div class="card-body">
                        <h5 class="card-title">C++</h5>
                        <p class="card-text">C++ es un lenguaje de programación diseñado en 1979 por Bjarne Stroustrup.
                                La intención de su creación fue extender al lenguaje de programación C mecanismos que
                                permiten la manipulación de objetos.
                        </p>
                        <a href="index.php?ctl=cpp" class="btn btn-primary">Leer más</a>
                </div>
        </div>

        <div class="card" style="width: 18rem;">
                <img src="includes/content/resources/img/csharp.jpg" class="card-img-top" alt="csharp">
                <div class="card-body">
                        <h5 class="card-title">C#</h5>
                        <p class="card-text">C# (pronunciado si sharp en inglés) es un lenguaje de programación
                                orientado a objetos desarrollado y estandarizado por Microsoft como parte de su
                                plataforma .NET... </p>
                        <a href="index.php?ctl=csharp" class="btn btn-primary">Leer más</a>
                </div>
        </div>

        <div class="card" style="width: 18rem;">
                <img src="includes/content/resources/img/java.png" class="card-img-top" alt="java">
                <div class="card-body">
                        <h5 class="card-title">Java</h5>
                        <p class="card-text">Java es un lenguaje de programación de propósito general, concurrente,
                                orientado a objetos...</p>
                        <a href="index.php?ctl=java" class="btn btn-primary">Leer más</a>
                </div>
        </div>
</div>