<article>

    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">C++</h1>
            <p class="lead">
                C++ es un lenguaje de programación diseñado en 1979 por Bjarne Stroustrup. La intención de su creación
                fue extender al lenguaje de programación C mecanismos que permiten la manipulación de objetos. En ese
                sentido, desde el punto de vista de los lenguajes orientados a objetos, el C++ es un lenguaje híbrido.
            </p>

            <p class="lead">
                Posteriormente se añadieron facilidades de programación genérica, que se sumaron a los paradigmas de
                programación estructurada y programación orientada a objetos. Por esto se suele decir que el C++ es un
                lenguaje de programación multiparadigma.
            </p>

            <p class="lead">
                El nombre "C++" fue propuesto por Rick Mascitti en el año 1983, cuando el lenguaje fue utilizado por
                primera vez fuera de un laboratorio científico. Antes se había usado el nombre "C con clases". En C++,
                la expresión "C++" significa "incremento de C" y se refiere a que C++ es una extensión de C.
            </p>
        </div>
    </div>

</article>