<article>

    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">C Sharp</h1>
            <p class="lead">
                C# (pronunciado si sharp en inglés) es un lenguaje de programación orientado a objetos desarrollado y
                estandarizado por Microsoft como parte de su plataforma .NET, que después fue aprobado como un estándar
                por la ECMA (ECMA-334) e ISO (ISO/IEC 23270). C# es uno de los lenguajes de programación diseñados para
                la infraestructura de lenguaje común.
            </p>

            <p class="lead">
                Su sintaxis básica deriva de C/C++ y utiliza el modelo de objetos de la plataforma .NET, similar al de
                Java, aunque incluye mejoras derivadas de otros lenguajes.
            </p>

            <p class="lead">
                El nombre C Sharp fue inspirado por el signo '#' que se compone de dos signos '+' pegados.
            </p>

            <p class="lead">
                Aunque C# forma parte de la plataforma .NET, ésta es una API, mientras que C# es un lenguaje de
                programación independiente diseñado para generar programas sobre dicha plataforma. Ya existe un
                compilador implementado que provee el marco Mono - DotGNU, el cual genera programas para distintas
                plataformas como Windows Microsoft, Unix, Android, iOS, Windows Phone, Mac OS y GNU/Linux.
            </p>
            
            <center>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/6EBNIgkrU74" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </center>
        </div>
    </div>

</article>