<article>

    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Java</h1>
            <p class="lead">
                Java es un lenguaje de programación de propósito general, concurrente, orientado a objetos, que fue
                diseñado específicamente para tener tan pocas dependencias de implementación como fuera posible. Su
                intención es permitir que los desarrolladores de aplicaciones escriban el programa una vez y lo
                ejecuten en cualquier dispositivo (conocido en inglés como WORA, o "write once, run anywhere"), lo que
                quiere decir que el código que es ejecutado en una plataforma no tiene que ser recompilado para correr
                en otra. Java es, a partir de 2012, uno de los lenguajes de programación más populares en uso,
                particularmente para aplicaciones de cliente-servidor de web, con unos diez millones de usuarios
                reportados
            </p>

            <p class="lead">
                El lenguaje de programación Java fue originalmente desarrollado por James Gosling, de Sun Microsystems
                (constituida en 1982 y posteriormente adquirida el 27 de enero de 2010 por la compañía Oracle) y
                publicado en 1995 como un componente fundamental de la plataforma Java de Sun Microsystems. Su sintaxis
                deriva en gran medida de C y C++, pero tiene menos utilidades de bajo nivel que cualquiera de ellos.
                Las aplicaciones de Java son compiladas a bytecode (clase Java), que puede ejecutarse en cualquier
                máquina virtual Java (JVM) sin importar la arquitectura de la computadora subyacente.
            </p>

            <p class="lead">
                La compañía Sun desarrolló la implementación de referencia original para los compiladores de Java,
                máquinas virtuales y librerías de clases en 1991, y las publicó por primera vez en 1995. A partir de
                mayo de 2007, en cumplimiento de las especificaciones del Proceso de la Comunidad Java, Sun volvió a
                licenciar la mayoría de sus tecnologías de Java bajo la Licencia Pública General de GNU. Otros también
                han desarrollado implementaciones alternas a estas tecnologías de Sun, tales como el Compilador de Java
                de GNU y el GNU Classpath.
            </p>
        </div>
    </div>

</article>