<article>

    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Squirrel</h1>
            <p class="lead">
                Squirrel (ardilla en inglés) es un lenguaje de programación de alto nivel imperativo y diseñado para
                que sea ligero. Es fácilmente integrable en aplicaciones, lo que lo convierte en un sustituto apropiado
                de Lua o JavaScript.
            </p>
            
            <p class="lead">
                Es usado por Code::Blocks, o videojuegos tales como Left 4 Dead 2 o Portal 2 donde se usa como scripts
                para eventos.
            </p>

            <p class="lead">
                El lenguaje se hizo público el 2003 bajo licencia zlib License. En noviembre del 2010, se
                relicenció el lenguaje a MIT License para que pudiera ser guardado el proyecto en Google Code. Ha sido
                desarrollado y mantenido por Alberto Demichelis.
            </p>
        </div>
    </div>

</article>